/*     */ package com.tenbyten.SG02;
/*     */ 
/*     */ import java.awt.Dimension;
/*     */ import java.awt.Toolkit;
/*     */ import java.util.ListResourceBundle;
/*     */ import javax.swing.KeyStroke;
/*     */ 
/*     */ 
/*     */ 
/*     */ public class SG02Bundle
/*     */   extends ListResourceBundle
/*     */ {
/*     */   public Object[][] getContents() {
/*  14 */     return this.contentsEnglish;
/*     */   }
/*     */   
/*  17 */   private Object[][] contentsEnglish = new Object[][] { { "Command.OK", "OK" }, { "Command.Cancel", "Cancel" }, { "Command.DeleteFiles", "Delete File(s)" }, { "Command.About", "About Songsheet Generator..." }, { "Command.About.Mn", new Integer(65) }, { "Command.Add", "Add >" }, { "Command.Add.Mn", new Integer(65) }, { "Command.MoveUp", "Move Up" }, { "Command.MoveUp.Mn", new Integer(85) }, { "Command.MoveDown", "Move Down" }, { "Command.MoveDown.Mn", new Integer(68) }, { "Command.PageSetup", "Page Setup..." }, { "Command.PageSetup.Mn", new Integer(71) }, { "Command.PageSetup.Acc", 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */         
/*  33 */         KeyStroke.getKeyStroke(80, 0x1 | Toolkit.getDefaultToolkit().getMenuShortcutKeyMask()) }, { "Command.Print", "Print..." }, { "Command.Print.Mn", new Integer(80) }, { "Command.Print.Acc", 
/*     */ 
/*     */         
/*  36 */         KeyStroke.getKeyStroke(80, Toolkit.getDefaultToolkit().getMenuShortcutKeyMask()) }, { "Command.Remove", "< Remove" }, { "Command.Remove.Mn", new Integer(82) }, { "Command.RemoveAll", "<< Remove All" }, { "Command.RemoveAll.Mn", new Integer(69) }, { "Command.Save.Plaintext", "Save Text..." }, { "Command.Save.Plaintext.Mn", new Integer(83) }, { "Command.Save.HTML", "Save HTML..." }, { "Command.Save.HTML.Mn", new Integer(83) }, { "Command.Save.ChordPro", "Save ChordPro..." }, { "Command.Save.ChordPro.Mn", new Integer(83) }, { "Command.Save.RTF", "Save Rich Text (RTF)..." }, { "Command.Save.RTF.Mn", new Integer(83) }, { "Command.Tab.General.Browse.SongPath", "Browse..." }, { "Command.Tab.General.Browse.SongPath.Mn", new Integer(66) }, { "Command.Tab.General.Browse.Editor", "Browse..." }, { "Command.Tab.General.Browse.Editor.Mn", new Integer(82) }, { "Command.Tab.General.Rescan", "Rescan" }, { "Command.Tab.General.PrintChords", "Print chords and instrumental comments" }, { "Command.Tab.General.PrintChords.Mn", new Integer(67) }, { "Command.Tab.General.PrintGrids", "Print guitar grids" }, { "Command.Tab.General.PrintGrids.Mn", new Integer(71) }, { "Command.Tab.General.PrintDoReMi", "Convert chords to do-re-mi" }, { "Command.Tab.General.PrintDoReMi.Mn", new Integer(68) }, { "Command.Tab.General.ReorderAAnThe", "Reorder titles that begin with 'A', 'An', or 'The'" }, { "Command.Tab.General.ReorderAAnThe.Mn", new Integer(69) }, { "Command.Tab.General.PrintTOC", "Print table of contents" }, { "Command.Tab.General.PrintTOC.Mn", new Integer(66) }, { "Command.Tab.General.PrintTOC.NPP", "Print table of contents on its own physical page" }, { "Command.Tab.General.TOCPageNumbers", "Include page numbers (when applicable)" }, { "Command.Tab.General.TOCPageNumbers.Mn", new Integer(0) }, { "Command.Tab.General.AutoNumberSongs", "Automatically number songs" }, { "Command.Tab.General.AutoNumberSongs.Mn", new Integer(65) }, { "Command.Tab.General.SongsPathRecurse", "Scan for songs in subfolders" }, { "Command.Tab.General.SongsPathRecurse.Mn", new Integer(70) }, { "Command.Tab.General.EncodingUTF8", "Use UTF-8 as default song file encoding" }, { "Command.Tab.General.EncodingUTF8.Mn", new Integer(85) }, { "Command.Tab.Print.Autospace", "Automatically single-space lines with no chords or lyrics" }, { "Command.Tab.Print.Autospace.Mn", new Integer(65) }, { "Command.Tab.Print.NPP", "Always start songs on a new physical page" }, { "Command.Tab.Print.NPP.Mn", new Integer(65) }, { "Command.Tab.Print.OverflowTitle", "Repeat song title on songs that overflow" }, { "Command.Tab.Print.OverflowTitle.Mn", new Integer(82) }, { "Command.Tab.Print.Footer.Physical.Only", "Physical page numbering only" }, { "Command.Tab.Print.SetFonts", "Set fonts" }, { "Command.Tab.Print.SetFonts.Mn", new Integer(70) }, { "Command.Tab.Print.Wrap.Titles", "Wrap long titles instead of reducing them" }, { "Command.Tab.Print.Wrap.Titles.Mn", new Integer(87) }, { "Command.Tab.Chords.Guitar", "Guitar mode" }, { "Command.Tab.Chords.Guitar.Mn", new Integer(71) }, { "Command.Tab.Chords.Ukulele", "Ukulele mode" }, { "Command.Tab.Chords.Ukulele.Mn", new Integer(85) }, { "Command.Tab.Chord.Capo.Use", "Use capo for key signatures and transposing" }, { "Command.Tab.Chord.Capo.Use.Mn", new Integer(67) }, { "Command.Tab.Chord.FriendlyGrids", "Print grids only for “friendly” key signatures:" }, { "Command.Tab.Chord.FriendlyGrids.Mn", new Integer(70) }, { "Command.Tab.DataValues.Add", "Add New" }, { "Command.Tab.DataValues.Add.Mn", new Integer(65) }, { "Command.Tab.DataValues.Edit", "Edit" }, { "Command.Tab.DataValues.Edit.Mn", new Integer(69) }, { "Command.Tab.DataValues.Delete", "Delete" }, { "Command.Tab.DataValues.Delete.Mn", new Integer(68) }, { "Command.Tab.FullScreen.StartFromSelected", "Start slideshow from the selected song" }, { "Command.Tab.FullScreen.StartFromSelected.Mn", new Integer(76) }, { "Command.Tab.FullScreen.Blank.First", "Start with blank slide" }, { "Command.Tab.FullScreen.Blank.First.Mn", new Integer(83) }, { "Command.Tab.FullScreen.Blank.Between", "Insert blank slide between songs" }, { "Command.Tab.FullScreen.Blank.Between.Mn", new Integer(73) }, { "Command.Tab.FullScreen.Blank.Last", "End with blank slide" }, { "Command.Tab.FullScreen.Blank.Last.Mn", new Integer(69) }, { "Command.Tab.FullScreen.Blank.Projector", "Slide projector-like blank between slides" }, { "Command.Tab.FullScreen.Blank.Projector.Mn", new Integer(74) }, { "Command.Tab.FullScreen.Control.Mouse", "Mouse-click control ( ← L R → )" }, { "Command.Tab.FullScreen.Control.Mouse.Mn", new Integer(77) }, { "Command.Tab.FullScreen.Control.Show", "Show control icons" }, { "Command.Tab.FullScreen.Control.Show.Mn", new Integer(87) }, { "Command.Tab.FullScreen.Foreground", "Set all fonts' color" }, { "Command.Tab.FullScreen.Background", "Set background" }, { "Command.Tab.FullScreen.OrphanControl", "Keep paragraphs together (orphan control)" }, { "Command.Tab.FullScreen.OrphanControl.Mn", new Integer(75) }, { "Command.FontSettings.Font", "Set..." }, { "Command.FontSettings.Font.Mn", new Integer(83) }, { "Command.FontSettings.Adjust", "Adjust" }, { "Command.FontSettings.Adjust.Mn", new Integer(65) }, { "Command.FontSettings.Copy", "Copy" }, { "Command.FontSettings.Copy.Mn", new Integer(67) }, { "Command.OSXFontChooser.Bold", "Bold" }, { "Command.OSXFontChooser.Bold.Mn", new Integer(66) }, { "Command.OSXFontChooser.Color", "Color" }, { "Command.OSXFontChooser.Color.Mn", new Integer(67) }, { "Command.OSXFontChooser.Italic", "Italic" }, { "Command.OSXFontChooser.Italic.Mn", new Integer(73) }, { "Command.Chordrc.Add", "Add New" }, { "Command.Chordrc.Add.Mn", new Integer(65) }, { "Command.Chordrc.Del", "Delete" }, { "Command.Chordrc.Del.Mn", new Integer(68) }, { "Command.Chordrc.Edit", "Edit custom chords" }, { "Command.Chordrc.Edit.Mn", new Integer(69) }, { "Command.Reminder.UpdateCheck", "Automatically check for updates" }, { "Command.Register.Donate", "Donate & Register" }, { "Command.Register.Donate.Mn", new Integer(68) }, { "Command.Register.EnterCode", "Enter registration code" }, { "Command.Register.EnterCode.Mn", new Integer(69) }, { "Command.Register.JustRun", "Maybe later" }, { "Command.Register.JustRun.Mn", new Integer(76) }, { "Command.Help", "Help" }, { "Command.Help.Mn", new Integer(72) }, { "Control.Spacing", new Dimension(10, 10) }, { "Control.Spacing.Quaqua", new Dimension(6, 6) }, { "Control.Size.Preferred.listboxSongs", new Dimension(200, 150) }, { "Control.Size.Min.listboxSongs", new Dimension(50, 50) }, { "Control.Size.Preferred.listboxPrint", new Dimension(150, 150) }, { "Control.Size.Min.listboxPrint", new Dimension(50, 50) }, { "Control.Columns.textfieldSongsPath", new Integer(25) }, { "Control.Columns.textfieldTranspose", new Integer(4) }, { "Control.Columns.textfieldFont", new Integer(5) }, { "Control.Columns.textfieldSpecialFormatting", new Integer(15) }, { "Label.SongsAvailable.Begin", "Songs available (" }, { "Label.SongsAvailable.End", "):" }, { "Label.SongsToPrint.Begin", "Songbook (" }, { "Label.SongsToPrint.End", " songs to print):" }, { "Label.SongsToPrint.End.0", "no songs selected to print):" }, { "Label.SongsToPrint.End.1", " song to print):" }, { "Label.KeyColumn.Capo.Begin", " (Capo " }, { "Label.KeyColumn.Capo.End", ")" }, { "Label.Tab.General.Output", "Output to: " }, { "Label.Tab.General.SongsEditor", "Song editor: " }, { "Label.Tab.General.SongsPath", "Path to songs: " }, { "Label.Tab.General.Transpose", "Transpose: " }, { "Label.Tab.General.TOCText", "Table of contents text: " }, { "Label.Tab.General.Half-Steps", " half-steps (all songs)" }, { "Label.Tab.General.Units", "Units:" }, { "Label.Tab.Chord.ChordsNoGrids", "Never print grids for chords: " }, { "Label.Tab.Chord.Grids.in", "Grid size (in.): " }, { "Label.Tab.Chord.Grids.mm", "Grid size (mm): " }, { "Label.Tab.Chord.Grids.min", "Min: " }, { "Label.Tab.Chord.Grids.max", "Max: " }, { "Label.Tab.Chord.Grids.spacing", "Spacing: " }, { "Label.Tab.Chord.Capo.MaxFret", "When transposing, place capo no higher than fret: " }, { "Label.Tab.Chord.Capo.PreferKeys", "Prefer transposing to “easy” keys: " }, { "Label.Tab.Printer.PageLayout", "Page layout: " }, { "Label.Tab.Printer.MarkChorus", "Mark chorus with: " }, { "Label.Tab.Printer.Margin.in", "Margins (in.): " }, { "Label.Tab.Printer.Margin.mm", "Margins (mm): " }, { "Label.Tab.Printer.Margin.Column", "Space between columns: " }, { "Label.Tab.Printer.Margin.2Column", "Additional left margin (for 2 discrete cells): " }, { "Label.Tab.Printer.Margin.Bottom", "Bottom " }, { "Label.Tab.Printer.Margin.Left", "Left " }, { "Label.Tab.Printer.Margin.Right", "Right " }, { "Label.Tab.Printer.Margin.Top", "Top " }, { "Label.Tab.Printer.Spacing.Normal", "Normal line spacing: " }, { "Label.Tab.Printer.Spacing.Chord", "Chord line spacing: " }, { "Label.Tab.Printer.Font.Size.Normal", "Normal font size: " }, { "Label.Tab.Printer.Font.Family.Normal", "Normal font family: " }, { "Label.Tab.Printer.Font.Family.Alternate", "Alternate font family: " }, { "Label.Tab.Printer.Tab.Chars", "Tab characters: " }, { "Label.Tab.Printer.FormatBox", "Special Formatting" }, { "Label.Tab.Printer.Footer", "Footer: " }, { "Label.Tab.Printer.Title", "Title: " }, { "Label.Tab.Printer.Subtitle", "Subtitle: " }, { "Label.Tab.HTML.LinkName", "Link name: " }, { "Label.Tab.HTML.SongBody", "Song body: " }, { "Label.Tab.HTML.Title", "Title: " }, { "Label.Tab.HTML.Subtitle", "Subtitle: " }, { "Label.Tab.HTML.Chord", "Chord: " }, { "Label.Tab.HTML.Lyric", "Lyric: " }, { "Label.Tab.HTML.Comment", "Comment: " }, { "Label.Tab.HTML.Chorus", "Chorus: " }, { "Label.Tab.HTML.Chorus.Overall", "Chorus overall: " }, { "Label.Tab.HTML.Tab", "Tab: " }, { "Label.Tab.HTML.NewSong", "New song: " }, { "Label.Tab.HTML.TOC", "TOC: " }, { "Label.Tab.HTML.TOC.Header", "TOC header: " }, { "Label.Tab.HTML.TOC.Contents", "TOC contents: " }, { "Label.Tab.HTML.Footer.Style", "Footer: " }, { "Label.Tab.HTML.Footer", "Footer text: " }, { "Label.Tab.FullScreen.Columns", "Columns per slide:" }, { "Label.Tab.FullScreen.Margins", "Margins (% of screen):" }, { "Label.Tab.FullScreen.Horz", "Horizontal:" }, { "Label.Tab.FullScreen.Vert", "Vertical:" }, { "Label.Tab.FullScreen.Font.Size", "Normal font size:" }, { "Label.Tab.FullScreen.Font.Note", "Note: full screen uses printer font families" }, { "Label.Tab.FullScreen.Image", "Background image:" }, { "Label.Tab.FullScreen.Footer", "Footer text:" }, { "Label.Tab.FullScreen.Device", "Display on screen:" }, { "Label.Tab.FullScreen.MainScreen", "Main Screen" }, { "Label.Tab.FullScreen.SecondaryScreen", "Secondary Screen" }, { "Label.Tab.DataValues.InfoLabel", "The data values below will apply to all song files:" }, { "Label.Tab.DataValues.Column.Key", "Key" }, { "Label.Tab.DataValues.Column.Value", "Value" }, { "Label.Tab.DataValues.Column.Usage", "Usage" }, { "Label.FontSettings.Font", "Font:" }, { "Label.FontSettings.Adjust", "<html><p>Adjust all font sizes relative to the current &quot;normal text&quot; font size" }, { "Label.FontSettings.Copy.Begin", "<html><p>Copy font settings (except color) from " }, { "Label.FontSettings.Copy.print", "Printer" }, { "Label.FontSettings.Copy.fullscreen", "Fullscreen" }, { "Label.FontSettings.Copy.End", " options settings" }, { "Label.FontSettings.Title", "Song title" }, { "Label.FontSettings.Subtitle", "Song Subtitle" }, { "Label.FontSettings.Normal", "Normal text" }, { "Label.FontSettings.Chord", "Chords" }, { "Label.FontSettings.Comment", "Comments" }, { "Label.FontSettings.Comment.Guitar", "Guitar/Instr. Comments" }, { "Label.FontSettings.Grid", "Chord grids" }, { "Label.FontSettings.Tab", "Tab notation" }, { "Label.FontSettings.Footer", "Footer text" }, { "Label.OSXFontChooser.Family", "Family" }, { "Label.OSXFontChooser.Style", "Style" }, { "Label.OSXFontChooser.Size", "Size" }, { "Label.Chordrc.Chords", "Custom chords:" }, { "Label.Chordrc.Name", "Name:" }, { "Label.Chordrc.Frets", "Frets:" }, { "Label.Chordrc.Fings", "Fingerings:" }, { "Label.Chordrc.Base", "Base fret:" }, { "Label.Chordrc.Key", "Key sig.:" }, { "Label.Chordrc.Definition", "Definition:" }, { "Label.Chordrc.Preview", "Preview:" }, { "Label.inches", "inches" }, { "Label.mm", "mm" }, { "Label.percent.screen", "% of screen" }, { "Menu.AllSongs", "All Songs" }, { "Menu.AllSongs.Mn", new Integer(83) }, { "Menu.AllSongs.PrintChords", "Print chords" }, { "Menu.AllSongs.PrintChords.Mn", new Integer(67) }, { "Menu.AllSongs.DontPrintChords", "Do not print chords" }, { "Menu.AllSongs.DontPrintChords.Mn", new Integer(78) }, { "Menu.File", "File" }, { "Menu.File.Mn", new Integer(70) }, { "Menu.File.New", "New Song File" }, { "Menu.File.New.Mn", new Integer(70) }, { "Menu.File.New.Acc", 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */         
/* 285 */         KeyStroke.getKeyStroke(78, Toolkit.getDefaultToolkit().getMenuShortcutKeyMask()) }, { "Menu.File.EditSong", "Edit Song" }, { "Menu.File.EditSongs", "Edit Songs" }, { "Menu.File.EditSong.Mn", new Integer(69) }, { "Menu.File.EditSong.Acc", 
/*     */ 
/*     */ 
/*     */         
/* 289 */         KeyStroke.getKeyStroke(69, Toolkit.getDefaultToolkit().getMenuShortcutKeyMask()) }, { "Menu.File.DeleteSong", "Delete Song" }, { "Menu.File.DeleteSongs", "Delete Songs" }, { "Menu.File.DeleteSong.Mn", new Integer(68) }, { "Menu.File.Import", "Import Song..." }, { "Menu.File.Import.Mn", new Integer(73) }, { "Menu.File.RescanSongs", "Rescan Songs" }, { "Menu.File.RescanSongs.Mn", new Integer(82) }, { "Menu.File.Reveal", "Reveal Songs in Finder" }, { "Menu.File.Print.TOC", "Print Table of Contents Only..." }, { "Menu.File.Print.TOC.Mn", new Integer(84) }, { "Menu.File.Songbook.New", "New Songbook" }, { "Menu.File.Songbook.New.Mn", new Integer(78) }, { "Menu.File.Songbook.New.Acc", 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */         
/* 302 */         KeyStroke.getKeyStroke(78, Toolkit.getDefaultToolkit().getMenuShortcutKeyMask() | 0x1) }, { "Menu.File.Songbook.Open", "Open Songbook..." }, { "Menu.File.Songbook.Open.Mn", new Integer(79) }, { "Menu.File.Songbook.Open.Acc", 
/*     */ 
/*     */         
/* 305 */         KeyStroke.getKeyStroke(79, Toolkit.getDefaultToolkit().getMenuShortcutKeyMask()) }, { "Menu.File.Songbook.Save", "Save Songbook..." }, { "Menu.File.Songbook.Save.Mn", new Integer(83) }, { "Menu.File.Songbook.Save.Acc", 
/*     */ 
/*     */         
/* 308 */         KeyStroke.getKeyStroke(83, Toolkit.getDefaultToolkit().getMenuShortcutKeyMask()) }, { "Menu.File.Songbook.SaveAs", "Save Songbook As..." }, { "Menu.File.Songbook.SaveAs.Mn", new Integer(65) }, { "Menu.File.Exit", "Exit" }, { "Menu.File.Exit.Mn", new Integer(88) }, { "Menu.Help", "Help" }, { "Menu.Help.Mn", new Integer(72) }, { "Menu.Help.Web", "On the Web" }, { "Menu.Help.Web.Mn", new Integer(87) }, { "Menu.Help.Web.Help", "Help Page" }, { "Menu.Help.Web.Help.Mn", new Integer(72) }, { "Menu.Help.Web.Home", "Home Page" }, { "Menu.Help.Web.Home.Mn", new Integer(79) }, { "Menu.Help.ReleaseNotes", "Show Release Notes" }, { "Menu.Help.ReleaseNotes.Mn", new Integer(82) }, { "Menu.Help.SGHelp", "Songsheet Generator Help" }, { "Menu.Help.FormattingCodes", "Formatting Codes Help" }, { "Menu.Help.FormattingCodes.Mn", new Integer(70) }, { "Menu.Options", "Options" }, { "Menu.Options.Mn", new Integer(79) }, { "Menu.Options.SetSongsPath", "Set Path to Songs..." }, { "Menu.Options.SetSongsPath.Mn", new Integer(69) }, { "Menu.Options.General", "General..." }, { "Menu.Options.General.Mn", new Integer(71) }, { "Menu.Options.General.Acc", 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */         
/* 332 */         KeyStroke.getKeyStroke(44, Toolkit.getDefaultToolkit().getMenuShortcutKeyMask()) }, { "Menu.Options.Fonts", "Fonts" }, { "Menu.Options.Fonts.Mn", new Integer(70) }, { "Menu.Options.Fonts.Bigger", "Make All Fonts Bigger" }, { "Menu.Options.Fonts.Bigger.Mn", new Integer(66) }, { "Menu.Options.Fonts.Bigger.Acc", 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */         
/* 339 */         KeyStroke.getKeyStroke(521, Toolkit.getDefaultToolkit().getMenuShortcutKeyMask()) }, { "Menu.Options.Fonts.Smaller", "Make All Fonts Smaller" }, { "Menu.Options.Fonts.Smaller.Mn", new Integer(83) }, { "Menu.Options.Fonts.Smaller.Acc", 
/*     */ 
/*     */ 
/*     */         
/* 343 */         KeyStroke.getKeyStroke(45, Toolkit.getDefaultToolkit().getMenuShortcutKeyMask()) }, { "Menu.Options.Printer", "Printer..." }, { "Menu.Options.Printer.Mn", new Integer(80) }, { "Menu.Options.Chords", "Chords / Grids..." }, { "Menu.Options.Chords.Mn", new Integer(67) }, { "Menu.Options.HTML", "HTML..." }, { "Menu.Options.HTML.Mn", new Integer(72) }, { "Menu.Options.FullScreen", "Full Screen..." }, { "Menu.Options.FullScreen.Mn", new Integer(70) }, { "Menu.Options.DataValues", "Data Values..." }, { "Menu.Options.DataValues.Mn", new Integer(68) }, { "Menu.Options.EnterCode", "Enter Registration Code..." }, { "Menu.Options.EnterCode.Mn", new Integer(82) }, { "Menu.Options.Chordrc", "Custom Chords..." }, { "Menu.Options.Chordrc.Mn", new Integer(67) }, { "Menu.Output", "Output Destination" }, { "Menu.Output.Mn", new Integer(79) }, { "Menu.Output.Printer", "Printer" }, { "Menu.Output.Printer.Mn", new Integer(80) }, { "Menu.Output.Plaintext", "Plain Text" }, { "Menu.Output.Plaintext.Mn", new Integer(84) }, { "Menu.Output.HTML", "HTML" }, { "Menu.Output.HTML.Mn", new Integer(72) }, { "Menu.Output.ChordPro", "ChordPro" }, { "Menu.Output.ChordPro.Mn", new Integer(67) }, { "Menu.Output.RTF", "Rich Text (RTF)" }, { "Menu.Output.RTF.Mn", new Integer(82) }, { "Menu.PageLayout", "Page Layout" }, { "Menu.PageLayout.Mn", new Integer(89) }, { "Menu.PageLayout.kOne", "1 Discrete Cell per Page" }, { "Menu.PageLayout.kOne.Mn", new Integer(49) }, { "Menu.PageLayout.kTwo", "2 Discrete Cells per Page" }, { "Menu.PageLayout.kTwo.Mn", new Integer(50) }, { "Menu.PageLayout.kFour", "4 Discrete Cells per Page" }, { "Menu.PageLayout.kFour.Mn", new Integer(52) }, { "Menu.PageLayout.kOneColumn", "1 Flowing Column per Page" }, { "Menu.PageLayout.kOneColumn.Mn", new Integer(70) }, { "Menu.PageLayout.kTwoColumn", "2 Flowing Columns per Page" }, { "Menu.PageLayout.kTwoColumn.Mn", new Integer(87) }, { "Menu.Transpose", "Transpose" }, { "Menu.Transpose.Mn", new Integer(84) }, { "Menu.Transpose.None", "None" }, { "Menu.Transpose.None.Mn", new Integer(78) }, { "Menu.Transpose.Other", "Other..." }, { "Menu.Transpose.Other.Mn", new Integer(79) }, { "Menu.Transpose.ByHalfStep", "By Half-step" }, { "Menu.Transpose.ByHalfStep.Mn", new Integer(72) }, { "Menu.Transpose.ToKey", "To Key" }, { "Menu.Transpose.ToKey.Mn", new Integer(75) }, { "Menu.Transpose.ToKey.NotThisMenu", "Right-click on a song in the print list to transpose by key name" }, { "Menu.Transpose.ToKey.SongNoKey", "The key signature has not been set for this song" }, { "Menu.Tab.Printer.kOne", "One Discrete Cell per Page" }, { "Menu.Tab.Printer.kTwo", "Two Discrete Cells per Page" }, { "Menu.Tab.Printer.kFour", "Four Discrete Cells per Page" }, { "Menu.Tab.Printer.kOneColumn", "One Flowing Column per Page" }, { "Menu.Tab.Printer.kTwoColumn", "Two Flowing Columns per Page" }, { "Menu.View", "View" }, { "Menu.View.Mn", new Integer(86) }, { "Menu.View.FullScreen", "Full Screen" }, { "Menu.View.FullScreen.Mn", new Integer(70) }, { "Menu.View.FullScreen.Acc", 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */         
/* 404 */         KeyStroke.getKeyStroke(70, Toolkit.getDefaultToolkit().getMenuShortcutKeyMask()) }, { "Menu.View.FullScreen.Now", "Instant Full Screen" }, { "Menu.View.FullScreen.Now.Mn", new Integer(73) }, { "Menu.View.FullScreen.Now.Acc", 
/*     */ 
/*     */         
/* 407 */         KeyStroke.getKeyStroke(70, Toolkit.getDefaultToolkit().getMenuShortcutKeyMask() | 0x1) }, { "Radio.Tab.HTML.Linked", "Use linked style sheet:" }, { "Radio.Tab.HTML.Linked.Mn", new Integer(76) }, { "Radio.Tab.HTML.Embedded", "Use embedded styles:" }, { "Radio.Tab.HTML.Embedded.Mn", new Integer(69) }, { "Radio.Tab.FullScreen.Columns.One", "One" }, { "Radio.Tab.FullScreen.Columns.Two", "Two" }, { "Text.About", "Please send feedback to christian@tenbyten.com.\nThanks!" }, { "Text.About.html", "<html>Please send feedback to <a href=\"mailto:christian@tenbyten.com\">christian@tenbyten.com</a>.<br>Thanks!" }, { "Text.Message.Overwrite", "<html><p><b>The file already exists.</b><p><br>Are you sure you want to overwrite the existing file?" }, { "Text.Message.ImportMulti", "<html><p><b>You have selected more than one file to import.</b><p><br>Songsheet Generator will automatically generate filenames and save the files in the songs folder.<p><br>Is this OK?" }, { "Text.Message.ImportRescanA", "<html><p><b>Successfully imported " }, { "Text.Message.ImportRescanB", " song(s).</b><p><br>Would you like Songsheet Generator to re-scan the songs folder to find the new song(s)?" }, { "Text.Message.ImportMaybeOK", "Songsheet Generator might not have imported this file as you expected.\nPlease check the file and make corrections." }, { "Text.Transpose", "Transpose (half steps):" }, { "Text.Imported", "*0* Imported song from file:" }, { "Text.Message.DoNotShowAgain", "Do not show this message again" }, { "Text.Message.Reminder.RTF.Bad", "<html><p><b>Please Note:</b><p><br>RTF is a document exchange format, and does not guarantee specific typesetting; the appearance of the RTF will not exactly match Songsheet Generator's printed output.  For best results, view the RTF in Microsoft Word or OpenOffice.<p><br>Understanding the limitations, are you ready to proceed?" }, { "Text.Message.UpdateCheck.Nag", "<html><p><b>Software Update Check</b><p><br>For registered users, Songsheet Generator can automatically check for software updates online.  <p><br>Do you want to automatically check for updates?" }, { "Text.Message.UpdateCheck.New", "<html><p><b>Update Available</b><p><br>A new version of Songsheet Generator is available.<p><br>Would you like to download it now?" }, { "Text.Message.UpdateCheck.Stop", "Do not check for updates" }, { "Text.Error.NoSongsPath", "<html><p><b>Songsheet Generator was unable to access your song files.</b><p><br>Please select a valid folder in the Options dialog, and make sure to check the \"Rescan\" box." }, { "Text.Error.NoSongEditor", "<html><p><b>Songsheet Generator is unable to edit the song with the selected editor.</b><p<br>Please double-check the song editor setting in the General Options Pane." }, { "Text.Error.Scan", "<html><p><b>Songsheet Generator encountered a problem while scanning your song files.</b><p<br>All of your song files may not be available." }, { "Text.Error.SGBOpen", "Songsheet Generator encountered a problem while opening your songbook file." }, { "Text.Error.SGBMissingSongs", "<html><p><b>Missing Songs</b><p><br>Not all of the songs in this songbook were found in your song list. Only %1$d of the %2$d songs in the songbook have been added to the print list." }, { "Text.Error.FullScreen.Unsupported", "Full Screen mode is not available on this display device." }, { "Text.Error.FullScreen.OSXJavaVer", "Full Screen mode is not supported on Macintosh OS X if the Java version is less than 1.4.2_05.\nPlease use Software Update to install Java 1.4.2 Update 1 or newer." }, { "Text.Error.Chord.Xpose", " is not a supported key for the transpose operation." }, { "Text.Error.Song.Overwrite", "<html><p><b>Invalid output file.</b><p><br>Writing over the top of your song files is not allowed." }, { "Text.Message.Register.Nag", "<html><p><b>Please donate and register!</b><p><br>Although Songsheet Generator will always be free to use, it is has cost a great deal of time and effort to create it.  <p><br>A monetary donation from you will help to support bug fixes, maintenance of internet services, and development of new features and improvements to this software.  <p><br>If you donate, you will receive a registration code that will permanently disable this dialog.  Otherwise, it will continue to appear from time to time.  <p><br>Thank you very much for your support.<br>" }, { "Text.Message.Register.EnterCode", "Enter your code here:" }, { "Text.Message.Register.Error", "<html><p><b>Songsheet Generator was unable to validate your registration code.</b><p><br>Please verify that you entered the code correctly.  <p><br>Would you like to try to enter it again?" }, { "Text.Message.Registered", "Registered" }, { "Text.Message.Unregistered", "Not registered" }, { "Text.Message.Register.Already", "<html><p><b>Songsheet Generator is already registered.</b><p><br>Would you like to enter another registration code?" }, { "Text.Message.Songbook.Exit", "<html><p><b>Unsaved Songbook</b><p><br>You have not saved your songbook.  Do you want to save it before exiting Songsheet Generator?" }, { "Text.Message.Songbook.Replace", "<html><p><b>Unsaved Songbook</b><p><br>You have not saved your songbook.  Do you want to save it before opening a new songbook?" }, { "Text.Error.NoSongsPath.MakeDefault", "<html><p><b>Songsheet Generator was unable to access song files in your documents folder.</b><p><br>Would you like to have  the sample song placed in your Documents folder?" }, { "Text.Message.DeleteSong", "<html><p>The selected song file will be deleted from your songs folder. <br><b>You cannot undo this action.</b> <br>Are you sure you want to delete the selected song file?" }, { "Text.Message.DeleteSongs", "<html><p>The selected song files will be deleted from your songs folder. <br><b>You cannot undo this action.</b> <br>Are you sure you want to delete the selected song files?" }, { "Text.Message.DeleteSongs.Double", "<html><p><b>Are you really sure?</b> <br>The selected song file(s) will not be moved to the Trash;<br>the source file(s) will be <b>completely erased!</b>" }, { "Text.ChorusMark.none", "No marking" }, { "Text.ChorusMark.line", "Line in margin" }, { "Text.ChorusMark.line.thick", "Thick line in margin" }, { "Text.ChorusMark.box", "Outlined box" }, { "Text.ChorusMark.box.light", "Outlined box (light)" }, { "Text.ChorusMark.box.fill.0.15", "Shaded box" }, { "Text.ChorusMark.indent.tab.1", "Single tab indent" }, { "Text.ChorusMark.indent.tab.2", "Double tab indent" }, { "Text.ChorusMark.line.tab.1", "Line with single tab indent" }, { "Text.Chord.New", "New chord" }, { "Title.Dialog.App", "Songsheet Generator" }, { "Title.Dialog.About", "About Songsheet Generator" }, { "Title.Dialog.Confirm", "Confirm" }, { "Title.Dialog.Error", "Error" }, { "Title.Dialog.Warning", "Warning" }, { "Title.Dialog.Options", "Options" }, { "Title.Dialog.File.WebBrowser", "Choose the web browser to use:" }, { "Title.Dialog.Transpose", "Transpose" }, { "Title.Dialog.OSXFontChooser", "Font" }, { "Title.Dialog.FontSettings.print", "Printer Font Settings" }, { "Title.Dialog.FontSettings.fullscreen", "Fullscreen Font Settings" }, { "Title.Dialog.Register.Nag", "Please Donate & Register" }, { "Title.Dialog.Register.EnterCode", "Enter Registration Code" }, { "Title.Dialog.Chordrc", "Custom Chord Editor" }, { "Title.Tab.General", "General" }, { "Title.Tab.Chords", "Chords / Grids" }, { "Title.Tab.Printer", "Printer" }, { "Title.Tab.HTML", "HTML" }, { "Title.Tab.FullScreen", "Full Screen" }, { "Title.Tab.DataValues", "Data Values" }, { "Title.Column.Title", "Song" }, { "Title.Column.Key", "Key" }, { "Title.Column.Artist", "Artist" },{ "Title.Column.Tag", "Tag" }, { "Songsheet Generator", "Songsheet Generator" }, { "Version", "Version 1.9.6.3  for  Mac OS X + Java" }, { "Version.Number", "1.9.6.3" }, { "Copyright", "Copyright (c) 2003-2019 Ten by Ten Software" } };
/*     */ }


/* Location:              C:\Users\m335138\Downloads\SG02\!\com\tenbyten\SG02\SG02Bundle.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.1.3
 */